### ISSUE TITLE
`Rails.cache.increment` does not work as documented

### ISSUE THREAD

**Issue by mstahl** [redis-store/redis-activesupport#101]
Ran into a really weird issue today while trying to use `Rails.cache.increment` through this gem. I know from #96 y'all are sunsetting support for this gem, but this might represent an incompatibility with Rails that's worth fixing, and I thought I'd write about this in case someone else runs into the same issue.

The call to `Rails.cache.increment('some-key')` works as one might expect it to, incrementing a key in Redis. From a cold cache, if I call `Rails.cache.increment('some-key')` when I look at 'some-key' in Redis I see `"1"`, which is perfectly sensible. The problem is that Rails's cache does not store anything directly like that; it instead stores a marshaled `ActiveSupport::Cache::Entry` object. So if I later try to retrieve the key with `Rails.cache.fetch` or `Rails.cache.read`, I get an error `incompatible marshal file format (can't be read)\n\tformat version 4.8 required; 49.48 given`. I also get similar marshal errors if I try to increment a key after writing it explicitly using Rails.cache.

Solution would be to marshal these the same way that ActiveSupport::Cache::Store does, or just make it clearer in the documentation that this method cannot be mixed with regular Rails cache reads/writes.

**Comment by tubbo** [comment]
@mstahl I can sorta reproduce your issue, but I get different errors:

```
[1] pry(main)> Rails.cache
=> #<ActiveSupport::Cache::RedisStore:0x00007f920f4a7880 @data=#<Redis client v4.0.1 for redis://localhost:6379/3>, @options={}>
[2] pry(main)> Rails.cache.increment('some-key')
=> 1
[3] pry(main)> Rails.cache.fetch('some-key')
ArgumentError: marshal data too short
```

```ruby
Rails.cache.delete('some-key') # => 1
Rails.cache.fetch('some-key') # => nil
Rails.cache.fetch('some-key') { 1 } # => 1
Rails.cache.increment('some-key') # => Redis::CommandError: ERR value is not an integer or out of range
Rails.cache.delete('some-key') # => 1
Rails.cache.fetch('some-key') { '1' } # => "1"
Rails.cache.increment('some-key') # Redis::CommandError: ERR value is not an integer or out of range
```
