### ISSUE TITLE
Release new gem version

### ISSUE THREAD

**Issue by ivanovv** [redis-store/redis-activesupport#108]
Given that 
> We are no longer accepting new features for this gem, only pull requests for security and compatibility fixes will be accepted.

that maybe not something you planned to do, but could you please release the current master as `5.0.5`? It has a fix for `TypeError: can't dup NilClass` error and I know I can use 
```
gem 'redis-activesupport', github: 'redis-store/redis-activesupport
```
in my `Gemfile`, but I prefer to keep the number of github gems to a minimum.

**Comment by tubbo** [comment]
sure thing, `5.0.5` is up on RubyGems right now.

**Comment by ivanovv** [comment]
You are my hero! ❤️
