### ISSUE TITLE
Still getting errors even with raise_errors: false

### ISSUE THREAD

**Issue by kewubenduben** [redis-store/redis-activesupport#109]
```
Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED) excluded from capture: Not configured to send/capture in environment 'development'

Redis::CannotConnectError (Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)):
```

I'm still getting this even when I've configured it with `raise_errors: false`. Is this an expected behavior? I'm expecting it to normally continue the code without errors.

```
➜  PROJECT git:(search) ✗ grep redis Gemfile.lock
    redis (4.0.1)
    redis-actionpack (5.0.2)
      redis-rack (>= 1, < 3)
      redis-store (>= 1.1.0, < 2)
    redis-activesupport (5.0.5)
      redis-store (>= 1.3, < 2)
    redis-rack (2.0.4)
      redis-store (>= 1.2, < 2)
    redis-rails (5.0.2)
      redis-actionpack (>= 5.0, < 6)
      redis-activesupport (>= 5.0, < 6)
      redis-store (>= 1.2, < 2)
    redis-store (1.5.0)
      redis (>= 2.2, < 5)
  redis-rails
```

**Comment by philipgiuliani** [comment]
It also crashes for me when redis is not available.

**Comment by tubbo** [comment]
@kewubenduben what were you trying to do that caused this error? we do rescue `Errno::ECONNREFUSED` if you configure `raise_errors: true`.

**Comment by kewubenduben** [comment]
@tubbo I was just testing if the code where caching is used will just ignore the errors if it's set to `raise_errors: false`. I temporarily disabled the Redis server to test it.

I'm using `redis-store` when for cache.

The thing is, I have no understanding yet if what I wanted is the expected result hence I had to check here.

The so far what I understand with `raise_errors: true` is that it catches the error but it just output the error and end the code at that point.

The goal is to have a continuous Rails app serving content even when Redis server went down.

Let me know if I'm not making sense.

**Comment by tubbo** [comment]
@kewubenduben it catches the error and returns whatever was provided in the `cache` block. in other words, rather than actually try to pull something from the cache, it just uses the hard-coded return value of the block.

so if you have a key `:foo` which has a value in Redis of "bar", and the Redis server is down, then `Rails.cache.fetch(:foo) { 'baz' }` will return `"baz"`, not `"bar"`.

**Comment by kewubenduben** [comment]
@tubbo, 

Sorry, I just found out that the problem was on `config.session_store`. Is there a way to have a rescued case like cache_store?

Thanks for the explanation, that helps on pointing out that my cache is working fine.

**Comment by PikachuEXE** [comment]
What is the behaviour when redis for session is offline? All null sessions?
Seems to be a valid reason to raise an error then?

**Comment by Xymist** [comment]
I'm also seeing this problem. With `raise_errors: false` I would expect the cache to just behave as if an absent/down Redis server was a simple cache miss, but instead I get a `Redis::CannotConnectError` exception. This is just for a `cache` block in the view, nothing complex. Is there anything I should try?

**Comment by tubbo** [comment]
@Xymist (and @PikachuEXE) I just released **redis-activesupport v5.2.0.pre** on RubyGems, give that version a whirl and see if it fixes your issue:

```ruby
gem 'redis-activesupport', '5.2.0.pre'
```

**Comment by PikachuEXE** [comment]
Updated
I don't think I have ever got any error when Redis server (as backend of cache store) is down
But session store is another issue

**Comment by tubbo** [comment]
Can we move this issue over to redis-store/redis-actionpack since that’s where the code lives for session storage?

**Comment by PikachuEXE** [comment]
I have tested `redis-activesupport v5.2.0.pre` for caching server, no error found when redis server down

**Comment by Xymist** [comment]
Upgrading to `redis-activesupport v5.2.0.pre` does appear to have fixed the issue when Redis is just used for caching; we don't use it for session storage yet so can't comment on that. Thank you! 😄

**Comment by tubbo** [comment]
hey folks I'm closing this issue since `redis-activesupport` isn't where session storage code lives. please open an issue on redis-store/redis-actionpack to continue the discussion.
