### ISSUE TITLE
Inconsistent Key marshalling for read_multi/fetch_multi

### ISSUE THREAD

**Issue by lxbrito** [redis-store/redis-activesupport#27]
If you try to pass Array/Hash like keys, or any option, specially namespace, to read_multi or fetch_multi, it will throw "NoMethodError: undefined method `match' for ...". 

It's similar to #23

**Comment by PikachuEXE** [comment]
@lxbrito #28 is merged. Please close this one

**Comment by radar** [comment]
I can do that :)
