### ISSUE TITLE
ActiveSupport limited to v3, won't use v4

### ISSUE THREAD

**Issue by Fustrate** [redis-store/redis-activesupport#42]
https://github.com/redis-store/redis-activesupport/commit/e2c87c41e23140aa8834daa72774ae17a45f886f#diff-ba4a050cd1468223b5f52ec47d6f9edaR23

```
irb(main):004:0> Gem::Dependency.new('', '~> 3').match?('', '3.5')
=> true
irb(main):005:0> Gem::Dependency.new('', '~> 3').match?('', '4.5')
=> false
```

Unfortunately, the ~> operator doesn't really work with single digits as "any version". This means Rails 4 applications, which require an AS4 gem, can't use this gem past v4.1.1. I'm pretty sure I'd recommend a constraint like `>= 3, < 5` instead.

**Comment by radar** [comment]
Patches welcome.
