### ISSUE TITLE
rescue Errno::EHOSTUNREACH

### ISSUE THREAD

**Issue by natesalisbury** [redis-store/redis-activesupport#44]
This is more of a question than an issue. 

Currently, the connection errors `Errno::ECONNREFUSED` and `Redis::CannotConnectError` are rescued when trying to access redis, example [here](https://github.com/redis-store/redis-activesupport/blob/d299520fde0aebfa24801f60ebe40a3973fc3164/lib/active_support/cache/redis_store.rb#L234). This morning our hosting service moved our redis server to another hypervisor (and we missed the email notification) which caused us some downtime with the error `Errno::EHOSTUNREACH` being raised from within the redis gem. Since we use redis for caching it would have been nice if those errors were rescued and the site continued running without caching. Is there any reason we wouldn't also want to rescue `Errno::EHOSTUNREACH` in addition to `Errno::ECONNREFUSED`? I'm happy to open a pull request if it would be accepted. 

I'm using:

- redis-activesupport 3.2.5
- redis 2.2.0
- redis-store 1.1.4
- redis-rails 3.2.4

From what I can tell being on the latest version of these gems wouldn't have made a difference in `Errno::EHOSTUNREACH` errors going unrescued.

**Comment by radar** [comment]
Good point. I do think we'll want to rescue that exception too. Please do open a pull request for that.
