### ISSUE TITLE
the #fetch_multi key?

### ISSUE THREAD

**Issue by hw676018683** [redis-store/redis-activesupport#50]
In the [#fetch_multi] (https://github.com/redis-store/redis-activesupport/blob/master/lib%2Factive_support%2Fcache%2Fredis_store.rb#L108) :
[this line] (https://github.com/redis-store/redis-activesupport/blob/master/lib%2Factive_support%2Fcache%2Fredis_store.rb#L115), the block's second params is `(name, _)`, which will only use first and drop the rest params.
 I see the [super](https://github.com/rails/rails/blob/v4.2.0/activesupport/lib/active_support/cache.rb#L369) code that is different from it.
Can you tell me why? Thanks.

**Comment by tubbo** [comment]
We eventually grab the value out of the Hash with `results.fetch()`, but we needed to do some extra processing to the value before we returned it and "saved" it as part of the memo.
