### ISSUE TITLE
delete_matched and Rails fragment caching

### ISSUE THREAD

**Issue by abernardes** [redis-store/redis-activesupport#56]
I'm having a problem using Rails' `expire_fragment` method and the RedisStore. Initially I tried calling `expire_fragment` using a regex as a parameter (as per the rails docs):

``` ruby
expire_fragment(/foo/)
```

and I got this message back:

```
Regexps aren't supported, please use string with wildcards.
```

So I tried:

``` ruby
expire_fragment("*foo*")
```

But it didn't work. All the keys containing `foo` were still there. I was looking into the `expire_fragment` method in [the Rails source](https://github.com/rails/rails/blob/e40518f5d44303ed91641b342a53bdfb32753de3/actionpack/lib/abstract_controller/caching/fragments.rb#L124). Here's the relevant part:

``` ruby
if key.is_a?(Regexp)
  cache_store.delete_matched(key, options)
else
  cache_store.delete(key, options)
end
```

So if I pass this method a string, Rails thinks I'm giving it a key and calls the `delete` method that deletes keys by exact match. But obviously there's no `*foo*` key on redis so expiring fails.

I'm open to give this issue a try and open a PR but all the solutions I thought have drawbacks and I couldn't decide which way to go. I was hoping the maintainers you could point me in the right direction. I thought of:
1. Accept a regex and call `source` on it. We could then call `expire_fragment(/*foo*/)`, `Regex#source` would give us `*foo*` and we'd use that as a matcher. This feels hacky and very confusing to me, because we'd be accepting a (potentially invalid) regex and not using it as such.
2. Overload `delete` to check if there are wildcards in the key. If so, call `delete_matched` with the key as a matcher. Otherwise, call `super`. Potential problem is, what if I actually have a `*foo*` key I want to delete?
3. Implementing something similar to #2 upstream. I doubt the Rails team would accept a PR with store-specific code though.

Of course I'm open to other suggestions. LMK what you think!

**Comment by rthbound** [comment]
@abernardes  Since wildcards are valid in keys, I don't think the wildcard support is a good idea.  I'd suggest making whatever changes are necessary in order to support regular expressions.

**Comment by abernardes** [comment]
The issue is, AFAIK redis itself don't support listing keys that match a regex. That would involve fetching all keys and filtering by regex match in memory.

Fetching all keys from a large production DB is a classic redis no-no, so I don't see a performant way of doing such. Any pointers?

**Comment by rthbound** [comment]
Fair... guides recommend SCAN: http://redis.io/commands/scan. @abernardes what's the shape of your envisioned solution?

**Comment by tubbo** [comment]
PR #74 seems to have implemented what you folks wanted here. Please take a look at master branch, I'll be releasing this as an update to `redis-activesupport` later today. In my own tests it didn't seem like it would have an effect if your keys are all Strings, which they typically are (right?).

**Comment by tubbo** [comment]
lol wrong issue

**Comment by tubbo** [comment]
@abernardes would love a look-over if you think #77 will fix your issue...
