### ISSUE TITLE
`fetch_multi` with nested keys (digests) not working

### ISSUE THREAD

**Issue by senny** [redis-store/redis-activesupport#65]
We are using the [jbuilder_cache_multi](https://github.com/yonahforst/jbuilder_cache_multi) gem and wanted to transition from a memcache based store to a Redis store. It looks like the current implementation of `fetch_multi` on the Redis store does not work with nested keys.

Here is the [relevant snippet in `jbuilder_cache_multi`](https://github.com/yonahforst/jbuilder_cache_multi/blob/master/lib/jbuilder_cache_multi/jbuilder_ext.rb#L12-L16). What happens is that the keys passed to `cache.fetch_multi` have the following format:

``` ruby
[<Object>, "<digest>"]
```

This leads to the following structure of `*names` in `fetch_multi`:

``` ruby
[
  [#<User id: 1>, "18fa3886e874288b209640bfccb619be"],
  [#<User id: 2>, "18fa3886e874288b209640bfccb619be"],
  [#<User id: 3>, "18fa3886e874288b209640bfccb619be"]
]
```

We tracked the issue down to [this line of the current fetch_multi implementation](https://github.com/redis-store/redis-activesupport/blob/master/lib/active_support/cache/redis_store.rb#L116):

``` ruby
names.inject({}) do |memo, (name, _)|
```

This drops the digest part. When a key is missing only `#<User id: 1>` will be yielded to the block passed to `fetch_multi`.

Something similar has been brought up in #50

**Comment by tubbo** [comment]
@senny Passing that second argument to the `yield` shouldn't break anything, because any code that passes a block into that method is only going to be taking one argument. Pull requests to fix this issue are welcome.

**Comment by tubbo** [comment]
PR #74 seems to have implemented what you folks wanted here. Please take a look at master branch, I'll be releasing this as an update to redis-activesupport later today. In my own tests it didn't seem like it would have an effect if your keys are all Strings, which they typically are (right?).
