### ISSUE TITLE
Use dup addresses to create connections on connection pools

### ISSUE THREAD

**Issue by pacoguzman** [redis-store/redis-activesupport#66]
If for some reason you modify the addresses variable in other place of your code, for example if you use it to setup the cache_store on Rails and Redis config on Sidekiq workers, and in both cases you're setting up a connection pool to Redis, because we're in a thread context a Sidekiq worker.

You could end mangling the addresses between both connection pools.
### Update

This is only needed from `connection_pool > 2.0.0` were the the connections are created as needed. I can see the development dependency is `connection_pool ~> 1.2.0` so I wasn't able to create a test to reproduce the bug.

Should I provide a patch without a test or bump the connection_pool development dependency and provide a proper patch

**Comment by pacoguzman** [comment]
I've updated the issue description the problem is raise for a change in how connection_pool creates connection (lazy or not)

**Comment by tubbo** [comment]
If we're not depending on connection_pool 2.x, why is this change necessary?

**Comment by pacoguzman** [comment]
Well, I faced the problem with connection_pool 2.x because before connections are created just when you instantiate the pool so if you modify later the addresses won't matter because the connections are already created.

connection_pool is just a development dependency for this gems, but maybe we can add the test only if you setup a specific version of connection_pool but that sounds weird for me

**Comment by tubbo** [comment]
@pacoguzman I can't see how duplicating the addresses would be a problem here, so why not? :) Anyway, please review the comment I made on your PR...it has some unnecessary changes in it.
