### ISSUE TITLE
Please release a new version with support for redis-store 1.3.0

### ISSUE THREAD

**Issue by jaredbeck** [redis-store/redis-activesupport#72]
The gemspec has already been udpated by https://github.com/redis-store/redis-activesupport/commit/622174a10038359d8fd7b60049dbc6a41bac2b4a, we just need to cut a release. Thanks.

**Comment by tubbo** [comment]
Fixed in https://github.com/redis-store/redis-activesupport/pull/73, it will be released later tonight.
