### ISSUE TITLE
nil value is not being sent back in read_multi

### ISSUE THREAD

**Issue by sairam** [redis-store/redis-activesupport#85]
```ruby
cache = RedisStore.new
cache.write(:test, nil)

expect(cache.read_multi([:test0, :test, :test1])).to eq ({test: nil}) # fails
expect(cache.read_multi([:test0, :test, :test1])).to_not eq ({}) # fails

```
found when redis store fails for test -  https://github.com/justinweiss/bulk_cache_fetcher/blob/master/test/bulk_cache_fetcher_test.rb#L130-L137

**Comment by tubbo** [comment]
@sairam this isn't actually using `Redis::Store`... https://github.com/justinweiss/bulk_cache_fetcher/blob/master/test/bulk_cache_fetcher_test.rb#L26-L27

**Comment by sairam** [comment]
Hi @tubbo, the gem is not using the store in the example, but our app uses Rails.cache which is a redis-store from active support using that gem. We had a problem with 4.1.5 and upgrading to 5.2 solved the issue except for 2 things. This is one of the test cases.

I just wanted to know/check if saving and retrieving of `nil` is an expectation or not from a general active-support cache provider.

**Comment by tubbo** [comment]
@sairam We do indeed filter out any `nil` values if you're using `#read_multi`...

- https://github.com/redis-store/redis-activesupport/blob/master/lib/active_support/cache/redis_store.rb#L107
- https://github.com/justinweiss/bulk_cache_fetcher/blob/master/lib/bulk_cache_fetcher.rb#L47
