### ISSUE TITLE
delete_matched only checks for regexps when a prefix is given

### ISSUE THREAD

**Issue by toupeira** [redis-store/redis-activesupport#9]
See https://github.com/redis-store/redis-activesupport/blob/e81c80ecb6db865c5a4b8bfb9ff36577a9a0fe6a/lib/active_support/cache/redis_store.rb#L217

Unless I'm missing something regexps aren't supported *without* prefixes either, right?

**Comment by tubbo** [comment]
Yeah but I think we check for `Regexp` somewhere else in the code...

**Comment by tubbo** [comment]
It would be better to document this method so that no one believes it's possible to pass a regexp into delete_matched. Even so, since AS::CacheStore seems to indicate that it's part of the API we're all implementing, I'm gonna chalk this up to human error.
