### ISSUE TITLE
Would you mind release `redis-actionpack` to rubygems.org #

### ISSUE THREAD

**Issue by larryzhao** [redis-store/redis-activesupport#94]
Would you mind release `redis-actionpack` as a minor release to rubygems.org so that we could use `redis-store 1.4.0`?

Thanks and Best Regards.

**Comment by tubbo** [comment]
You don't need a new version of redis-activesupport to take advantage of redis-store 1.4.0, we just don't require you to install redis-store 1.4.0 in order to use redis-activesupport. You can add the following to Gemfile to install redis-store 1.4.0 on your application:

```ruby
gem 'redis-store', '~> 1.4.0'
```

**Comment by larryzhao** [comment]
@tubbo I think you misunderstood me. The current version released to `rubygems.org` has the dependency specified as `''redis-store',   '~> 1.3.0'`. 

Since you've already updated the gemspec on master branch for months. Would you mind release a minor version to `rubygems.org`?

Thanks and Best Regards.

**Comment by tubbo** [comment]
hey @larryzhao just so you know **v5.0.3** of redis-activesupport is already released with loosened gem dependency constraints, this one should be OK to use with redis-store 1.4
